import type {Metadata} from 'next'
import {Noto_Sans_Thai_Looped} from 'next/font/google'
// import '@ant-design/flowchart/dist/index.css'
import './globals.css'

import Navbar from '@/components/layouts/Navbar'
import Sidebar from '@/components/layouts/Sidebar'
import {MenubarProvider} from '@/context/MenubarContext'

const inter = Noto_Sans_Thai_Looped({subsets: ['latin'], weight: '400'})

export const metadata: Metadata = {
  title: 'SET Easy Money Management System',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MenubarProvider>
          <Navbar />
          <main
            className='flex flex-row w-full relative pt-[85px]'
            style={{
              backgroundColor: 'rgba(242, 249, 255, 1)',
            }}
          >
            <Sidebar />
            <section className='w-full p-6 pl-[104px]'>
              {children}
            </section>
          </main>
        </MenubarProvider>
      </body>
    </html>
  )
}
